"""empty message

Revision ID: 497962b9b963
Revises: 8a4ca3d0f58a
Create Date: 2020-08-12 09:29:31.489241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497962b9b963'
down_revision = '8a4ca3d0f58a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('holidays_ibge_code_fkey', 'holidays', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('holidays_ibge_code_fkey', 'holidays', 'location', ['ibge_code'], ['ibge_code'])
    # ### end Alembic commands ###
