"""empty message

Revision ID: 8a4ca3d0f58a
Revises: 
Create Date: 2020-08-11 17:43:57.583609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4ca3d0f58a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('ibge_code', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ibge_code')
    )
    op.create_table('holidays',
    sa.Column('holiday_id', sa.Integer(), nullable=False),
    sa.Column('ibge_code', sa.Integer(), nullable=True),
    sa.Column('holiday_name', sa.String(), nullable=True),
    sa.Column('holiday_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ibge_code'], ['location.ibge_code'], ),
    sa.PrimaryKeyConstraint('holiday_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holidays')
    op.drop_table('location')
    # ### end Alembic commands ###
